### PR TITLE
🌱  WIP: Improves cluster module check

### PR DESCRIPTION
**Pull request by srm09**
**What does this PR do, and why is it needed?**

**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes #

**Are there any special notes for your reviewer**:

**Please add a release note if necessary**:

```release-note

```

### CODE REVIEW

**Comment by akutz** [comment]
There's no PR description of commit message body telling me what this does other than a vague "Improves"

Can you please provide a high-level tl;dr of what this does and how? Because a large part of the optimization is on the vpxd side and its OOM issues.

**Comment by srm09** [comment]
>There's no PR description of commit message body telling me what this does other than a vague "Improves"
Can you please provide a high-level tl;dr of what this does and how? Because a large part of the optimization is on the vpxd side and its OOM issues.

Actually wanted to check something on the `verify-codegen` github action. Hence raised this PR to see if it has the same issue or not. 
I will rework the commit message and the PR description to include the relevant why

**Comment by akutz** [comment]
Hey @srm09 ,

Does this consider stretched Supervisor? If you look at the history, the modules used to _not_ consider the cluster per https://github.com/vmware-tanzu/vm-operator/commit/e5f3496423a2b95580f8109dfbad98c32816df0e#diff-c2821172102c8b81138e4608d22c6c86f1a67177a9d63774ffae48cd9022f95fL660-L708, but then with HA, the cluster ref was added.

**Comment by bryanv** [comment]
> Hey @srm09 ,
> 
> Does this consider stretched Supervisor? If you look at the history, the modules used to _not_ consider the cluster per [e5f3496#diff-c2821172102c8b81138e4608d22c6c86f1a67177a9d63774ffae48cd9022f95fL660-L708](https://github.com/vmware-tanzu/vm-operator/commit/e5f3496423a2b95580f8109dfbad98c32816df0e#diff-c2821172102c8b81138e4608d22c6c86f1a67177a9d63774ffae48cd9022f95fL660-L708), but then with HA, the cluster ref was added.

Yah this MR confuses - and worries - me a little. Are we saying that lookup is faster _without_ the CCR param?!? (that seems odd but the API can ignore the param or something). My understand is that the ClusterMod are scoped per CCR so like to have the validation that the module ID we're passing in is for the CCR we're expecting. There's various issues with this API but this seems to be a step backwards.

**Comment by srm09** [comment]
/close

The current ClusterModule [ListMembers](https://vdc-download.vmware.com/vmwb-repository/dcr-public/c2c7244e-817b-40d8-98f3-6c2ad5db56d6/af6d8ff7-1c38-4571-b72a-614ac319a62b/structures/com/vmware/vcenter/cluster/modules/vm/members/svc.get_result-structure.html) API does not provide any information regarding the CCR MoRef which is necessary to confirm the association of the module to the CCR. This is paramount in case of the stretched cluster cases, and hence closing this for now until the existence of an improved API which gives the required details.

**Pull request closed without merging**
