### PR TITLE
✨ Use Symlink or Docker for generate-go-conversions fallback

### PR DESCRIPTION
**Pull request by akutz**
**What does this PR do, and why is it needed?**

This patch updates the `generate-go-conversions` target to support either Symlink (default) or Docker as a fallback for running the `conversion-gen` tool when the local sources are not cloned in the path expected by said tool.
    
The env var `CONVERSION_GEN_FALLBACK_MODE` may be used to set the fallback mode. This defaults to `symlink`, but can also be set to `docker`.

**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes `NA`

**Are there any special notes for your reviewer**:

The fastest way to verify this PR's symlink mode is with Docker:

```shell
# works on intel & arm linux/mac systems
GOLANG_IMAGE="golang:$(go env GOVERSION | cut -c3-)" && \
[ "$(go env GOHOSTARCH)" = "arm64" ] && GOLANG_IMAGE="arm64v8/${GOLANG_IMAGE}"; \
docker run -it --rm "${GOLANG_IMAGE}" bash -c \
  'git clone https://github.com/akutz/vm-operator /vmop && \
  git -C /vmop checkout bugfix/generate-go-conversions && \
  rm -f /vmop/api/v1alpha1/zz_generated.conversion.go && \
  git -C /vmop status && \
  make -C /vmop generate-go-conversions && \
  git -C /vmop status'
```

The above command will:

1. Start a Golang container
2. Clone this fork of VM Op to `/vmop` in the container, which is outside the `GOPATH`
3. Checkout this branch
4. Delete the generated conversions source
5. Run `make generate-go-conversions` 
6. Illustrate the generated source is recreated

**Please add a release note if necessary**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akutz** [comment]
FWIW, I was going to just use a symlink to set up a temp `GOPATH`, but there's no clean way to do this due to [this bug](http://savannah.gnu.org/bugs/index.php?57914#comment0) in GNU Make, where the `abspath` function resolves symlinks instead like `realpath`, despite the documented, expected behavior.

**Comment by akutz** [comment]
> FWIW, I was going to just use a symlink to set up a temp `GOPATH`, but there's no clean way to do this due to [this bug](http://savannah.gnu.org/bugs/index.php?57914#comment0) in GNU Make, where the `abspath` function resolves symlinks instead like `realpath`, despite the documented, expected behavior.

I cheated around the symlink limitation by allowing `ROOT_DIR` and `GOPATH` to be sent in via env vars instead of using their discovered values.

**Comment by srm09** [comment]
For Intel Macs
```bash
$ GOLANG_IMAGE="golang:$(go env GOVERSION | cut -c3-)" && \
docker run -it --rm "${GOLANG_IMAGE}" bash -c \
  'git clone https://github.com/akutz/vm-operator /vmop && \
  git -C /vmop checkout bugfix/generate-go-conversions && \
  rm -f /vmop/api/v1alpha1/zz_generated.conversion.go && \
  git -C /vmop status && \
  make -C /vmop generate-go-conversions && \
  git -C /vmop status'
```

**Comment by akutz** [comment]
> For Intel Macs, test via
> 
> ```shell
> $ GOLANG_IMAGE="golang:$(go env GOVERSION | cut -c3-)" && \
> docker run -it --rm "${GOLANG_IMAGE}" bash -c \
>   'git clone https://github.com/akutz/vm-operator /vmop && \
>   git -C /vmop checkout bugfix/generate-go-conversions && \
>   rm -f /vmop/api/v1alpha1/zz_generated.conversion.go && \
>   git -C /vmop status && \
>   make -C /vmop generate-go-conversions && \
>   git -C /vmop status'
> ```

Why is this necessary? The original example includes Intel Macs as well:

```shell
GOLANG_IMAGE="golang:$(go env GOVERSION | cut -c3-)" && \
[ "$(go env GOHOSTARCH)" = "arm64" ] && GOLANG_IMAGE="arm64v8/${GOLANG_IMAGE}" && \
docker run -it --rm "${GOLANG_IMAGE}" bash -c \
  'git clone https://github.com/akutz/vm-operator /vmop && \
  git -C /vmop checkout bugfix/generate-go-conversions && \
  rm -f /vmop/api/v1alpha1/zz_generated.conversion.go && \
  git -C /vmop status && \
  make -C /vmop generate-go-conversions && \
  git -C /vmop status'
```

If it's an Intel mac, the image defaults to normal Golang.

**Review by srm09 — COMMENTED** [review]
There is duplication between `GOPATH_PROJECT_SLUG` and `VMOP_PREFIX`, not a big deal but my suggestion is we rename `GOPATH_PROJECT_SLUG` => `PROJECT_SLUG` and use that in all places.

**Review by srm09 — APPROVED** [review]

**Pull request merged**
