### PR TITLE
Consume latest image-registry API changes

### PR DESCRIPTION
**Pull request by acharyasreej**
This change consumes the latest image registry API changes after getting the K8s APIs reviewed.

# Testing Done:
1. Built VM operator with this change.
2. Built Supervisor with overridden image-registry-operator and vm-operator components.
4. Deployed a testbed with the new Supervisor and verified the feature end-to-end.
5. Tested b2b upgrade and verified that the resources get updated and reconciled.
6. Ran the image registry, VM operator and TKGs end-to-end tests on the upgraded testbed.

### CODE REVIEW

**Comment by dilyar85** [comment]
I triggered an internal e2e test with this PR and it passed. Adding the `testing-done-e2e-fast` label accordingly to unblock merging this PR.

**Comment by acharyasreej** [comment]
> LGTM! Just to clarify, are you planning to create a follow-up PR that directly consumes the upstream image-registry-api once the repo is public?

Thanks for reviewing the changes Sai! Yes I can work on the change to consume the upstream VM Image Registry APIs after making the repo public.

**Review by aruneshpa — COMMENTED** [review]
LGTM.

**Review by aruneshpa — APPROVED** [review]

**Review by zyiyi11 — APPROVED** [review]
LGTM

**Pull request merged**
